# Generated by Django 3.1.7 on 2021-03-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='propic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
