# Generated by Django 3.1.7 on 2021-03-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_propic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='propic',
            field=models.ImageField(blank=True, default='default_pic.jpg', null=True, upload_to=''),
        ),
    ]
