# Generated by Django 3.2.5 on 2021-07-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210711_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
