# Generated by Django 3.2.5 on 2021-07-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_articles_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
