# Generated by Django 3.2.5 on 2021-07-12 12:50

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_articles_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='preview',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=150),
        ),
    ]
