# Generated by Django 3.2.5 on 2021-07-14 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_comments_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
