# Generated by Django 3.2.5 on 2021-07-14 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
