# Generated by Django 3.1.7 on 2021-03-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
