# Generated by Django 3.1.7 on 2021-03-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_items_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='items',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
