# Generated by Django 3.1.7 on 2021-03-18 10:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20210317_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
