# Generated by Django 3.1.7 on 2021-03-22 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20210318_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'ordering': ['name']},
        ),
    ]
