# Generated by Django 3.2.5 on 2021-07-11 10:01

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_items_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
