# Generated by Django 3.2.5 on 2021-07-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_remove_articles_preview'),
        ('portfolio', '0007_alter_items_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='tags',
            field=models.ManyToManyField(max_length=100, to='blog.Skills'),
        ),
    ]
