# Generated by Django 3.2.5 on 2021-07-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_items_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='image',
            field=models.ImageField(blank=True, default='default-placeholder.png', null=True, upload_to=''),
        ),
    ]
